headers = {
    'accept': '*/*',
    'accept-language': 'ko,ko-KR;q=0.9,en-HK;q=0.8,en;q=0.7',
    # 'content-length': '0',
    # 'cookie': '__Secure-3PAPISID=sjb-Ge5Kj4BjH_QD/ACM0MsjiOkQbbTxsT; __Secure-3PSID=g.a000oAh8uBaW84PnGjpfbBsVw2QiD5TQmWXeVmPlg8Vhhqyuti5KbYqEuO4a9n-n1cP5c5sN0gACgYKAZcSARISFQHGX2MiUWVuK-Y3IENhoBSliY_p6xoVAUF8yKrsGZICjEXBTEYTXC-ySfVs0076; NID=518=ljjsmeDC3bqAxXOe9XQo1OyjWau8jN9T1FfO_eC_KMeq2MHxdlPqMAV36aFbIo0pP0jmZcQtaBE6kEFDStISpIG1Artamr49EwQcDJ86DM8Nxme5MDAG8KO7xtuTNZwtbqPPNXz9qg4hjrZ7pkw0DwvyPoMtzjDdSsEfm9qGdJdYsdTzJ_vgtHgvdOaxMeRBCsTJtC5BkGtcOmx0HWi2lQ01Cd748A7YHcn2kLxYsS3tCG9LSrbGv6TDUeymbhggtfcd77JdJCF2Byi5iiFkaaQ0x9GsDJ_8dZn64NdUvb7GVzw5jSWjpYbYOuvVPcaJjcYH1-I0BeEV0pC6_LHJruImTpo6UHh9NadQOagZN5n1j31iAdH77_PGNx-7XE6E3HhSOcQzdWMNLAkJrkLEa-bxIclx2jTvl9ERabJQIbD6_Hf3QaXWBYE; __Secure-3PSIDTS=sidts-CjIBQlrA-EzHBJsvHIxQ1pAMubFUlbcO9PsFLu-oDhmSCACSTVZGOTorAFJTloPFV_DFJhAA; __Secure-3PSIDCC=AKEyXzWCtLjEBv9MycpScfpvvuNEED4gtnZL_uKzeK8lz-L-gzACb3zFBTZiEvBs3OykIntAl4s',
    'origin': 'https://www.pieceofcreative.com',
    'priority': 'u=1, i',
    'referer': 'https://www.pieceofcreative.com/',
    'sec-ch-ua': '"Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': '"Android"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'no-cors',
    'sec-fetch-site': 'cross-site',
    'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36',
    'x-client-data': '',
}