name: Black

on:
  pull_request_target:
    types: [closed]

jobs:
  build:
    if : github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==24.10.0
    - name: Format with black
      run: |
        black $(git ls-files '*.py')
        git config --global user.email "bsch0111@naver.com"
        git config --global user.name "bsch0111"
        git add .
        git commit -m "Format with black"
        git push origin main
